export const ROUTES = {
  ONBOARDING: 'onboarding',
  LOGIN: 'login',
  SIGNUP: 'signup',
  HOME: 'home',
  SEARCH: 'search',
  CASE_DETAIL: 'case-detail',
  CONSTITUTION_HUB: 'constitution-hub',
  NOTEBOOK: 'notebook',
  FLASHCARDS: 'flashcards',
  STUDY_SESSION: 'study-session',
  PROFILE: 'profile',
  FOLDER_DETAIL: 'folder-detail',
  DECK_DETAIL: 'deck-detail',
};
